// 图标映射 - 使用 unicode 字符或文字
export const Icons = {
  Home: '⌂',
  Timer: '⏱',
  Activity: '✦',
  User: '☺',
  Bell: '🔔',
  MapPin: '⌖',
  Calendar: '✸',
  Plus: '+',
  Search: '⌕',
  Zap: '⚡',
  ChevronRight: '›',
  ChevronLeft: '‹',
  Play: '►',
  Stop: '■',
  Award: '★',
  Check: '✓',
  SquareIcon: '▢',
  MessageCircle: '✉',
  QrCode: '⌗',
  Scan: '▤',
  Send: '➤',
  Heart: '❤',
  More: '⋯',
  Radar: '☄',
  Flame: '🔥',
  Coffee: '☕',
  Chat: '✆',
  Female: '♀',
  Male: '♂',
  Clock: '⏰',
  TrendingUp: '⇡',
  Dumbbell: '➹',
  XCircle: '✕',
  UserPlus: '➕',
  UserCheck: '✔',
  Loader: '⟳',
  Filter: '⚙',
  ArrowDownCircle: '⌄',
  Power: '⏻',
  Sword: '⚔',
  Users: '👥',
  Handshake: '⇆',
  Help: '?',
  Alert: '!',
  Feather: '✤',
  ArrowLeft: '←',
  Share: '⇪',
  Settings: '⚙',
  Shield: '⛨',
  LogOut: '⇦',
  Edit: '✎',
  Smartphone: '☎',
  Rotate: '⟳',
  Image: '🖼'
}

